# Meadow.CLI pipeline
# Reference: https://aka.ms/yaml

trigger:
- master
- develop

variables:
  solution: '**/MeadowCLI.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  internalFeedName: 'Meadow'
  preReleasePackageBranch: 'refs/heads/develop'
  meadowNugetServiceConnectionName: 'Meadow_Nuget'

pool:
  vmImage: windows-2019

stages:
- stage: Build
  jobs:
    - job: Build_Solution
      steps:
        - task: NuGetToolInstaller@1
        - task: NuGetCommand@2
          inputs:
            feedsToUse: 'select' 
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: CopyFiles@2
          inputs:
            Contents: 'MeadowCLI\bin\Release\net472\*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\Meadow.CLI'
            cleanTargetFolder: true
            flattenFolders: true
        - task: CopyFiles@2
          inputs:
            Contents: '**\*.nupkg'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            cleanTargetFolder: true
            flattenFolders: true
        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: artifacts